import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatProvider from "@/providers/ChatProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gemini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
